services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  # consumer:
  #   build: .
  #   command: python -m consumer.worker
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/taskdb
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     db:
  #       condition: service_started

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
